//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2_Trab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.ColaboradorEquipas = new HashSet<ColaboradorEquipa>();
        }
    
        public decimal id { get; set; }
        public string email { get; set; }
        public Nullable<decimal> telemovel { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string endereco { get; set; }
        public string profissao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColaboradorEquipa> ColaboradorEquipas { get; set; }
    }
}
