//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2_Trab2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class L51NG7Entities : DbContext
    {
        public L51NG7Entities()
            : base("name=L51NG7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ativo> Ativoes { get; set; }
        public virtual DbSet<ColaboradorEquipa> ColaboradorEquipas { get; set; }
        public virtual DbSet<Competencia> Competencias { get; set; }
        public virtual DbSet<Equipa> Equipas { get; set; }
        public virtual DbSet<Funcionario> Funcionarios { get; set; }
        public virtual DbSet<Intervencao> Intervencaos { get; set; }
        public virtual DbSet<IntervencaoEquipa> IntervencaoEquipas { get; set; }
        public virtual DbSet<Tipo> Tipoes { get; set; }
    }
}
