//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2_Trab2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipa()
        {
            this.ColaboradorEquipas = new HashSet<ColaboradorEquipa>();
            this.IntervencaoEquipas = new HashSet<IntervencaoEquipa>();
        }
    
        public decimal id { get; set; }
        public string localizacao { get; set; }
        public Nullable<int> n_elementos { get; set; }
        public Nullable<int> intervencoes_atribuidas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColaboradorEquipa> ColaboradorEquipas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntervencaoEquipa> IntervencaoEquipas { get; set; }
    }
}
