//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI2_Trab2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumoInter
    {
        public decimal inter_id { get; set; }
        public string descricao { get; set; }
        public string inter_estado { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_fim { get; set; }
        public Nullable<int> periodicidade { get; set; }
        public Nullable<decimal> ativo_id { get; set; }
        public Nullable<decimal> parent_id { get; set; }
        public string nome { get; set; }
        public System.DateTime data_aquisicao { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string localizacao { get; set; }
        public decimal ativo_estado { get; set; }
        public Nullable<decimal> id_tipo { get; set; }
    }
}
