//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabalho2
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntervencaoEquipa
    {
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_fim { get; set; }
        public decimal id_equipa { get; set; }
        public decimal id_intervencao { get; set; }
    
        public virtual Equipa Equipa { get; set; }
        public virtual Intervencao Intervencao { get; set; }
    }
}
